# Generated by Django 4.1.4 on 2022-12-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentelement",
            old_name="desciption",
            new_name="description",
        ),
    ]
