# Generated by Django 4.1.4 on 2022-12-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentlist", "0002_rename_desciption_contentelement_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=30, verbose_name="Job Title"),
                ),
                (
                    "job_description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                ("rating", models.FloatField(verbose_name="Rating")),
                (
                    "estimated_salary",
                    models.CharField(max_length=30, verbose_name="Estimated Salary"),
                ),
                ("min_salary", models.IntegerField(verbose_name="min_salary")),
                ("max_salary", models.IntegerField(verbose_name="max_salary")),
                ("average_salary", models.IntegerField(verbose_name="average_salary")),
                ("python_required", models.BooleanField(verbose_name="python_yn")),
                ("excel_required", models.BooleanField(verbose_name="excel")),
                ("r_lang_required", models.BooleanField(verbose_name="R_yn")),
                ("spark_required", models.BooleanField(verbose_name="spark")),
                ("company_size", models.IntegerField(verbose_name="Size")),
            ],
        ),
        migrations.DeleteModel(
            name="ContentElement",
        ),
    ]
