# Generated by Django 4.1.4 on 2022-12-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentlist", "0003_vacancy_delete_contentelement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="average_salary",
            field=models.IntegerField(blank=True, verbose_name="average_salary"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="company_size",
            field=models.IntegerField(blank=True, verbose_name="Size"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="estimated_salary",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Estimated Salary"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="excel_required",
            field=models.BooleanField(blank=True, verbose_name="excel"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="max_salary",
            field=models.IntegerField(blank=True, verbose_name="max_salary"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="min_salary",
            field=models.IntegerField(blank=True, verbose_name="min_salary"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="python_required",
            field=models.BooleanField(blank=True, verbose_name="python_yn"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="r_lang_required",
            field=models.BooleanField(blank=True, verbose_name="R_yn"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="rating",
            field=models.FloatField(blank=True, verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="spark_required",
            field=models.BooleanField(blank=True, verbose_name="spark"),
        ),
    ]
