# Generated by Django 4.1.4 on 2022-12-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentlist", "0006_alter_vacancy_average_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="estimated_salary",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Estimated Salary"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="job_description",
            field=models.CharField(max_length=5000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="job_title",
            field=models.CharField(max_length=60, verbose_name="Job Title"),
        ),
    ]
